//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SealTest.NSTWsProvider {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web.nts.nsp.nsi.dk/", ConfigurationName="NSTWsProvider.NtsWSProvider")]
    public interface NtsWSProvider {
        
        // CODEGEN: Generating message contract since the operation invoke is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://web.nts.nsp.nsi.dk/NtsWSProvider/invoke", ReplyAction="http://web.nts.nsp.nsi.dk/NtsWSProvider/invokeResponse")]
        SealTest.NSTWsProvider.invokeResponse invoke(SealTest.NSTWsProvider.invoke request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.nts.nsp.nsi.dk/NtsWSProvider/invoke", ReplyAction="http://web.nts.nsp.nsi.dk/NtsWSProvider/invokeResponse")]
        System.Threading.Tasks.Task<SealTest.NSTWsProvider.invokeResponse> invokeAsync(SealTest.NSTWsProvider.invoke request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invoke {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invoke", Namespace="http://web.nts.nsp.nsi.dk/", Order=0)]
        public object invoke1;
        
        public invoke() {
        }
        
        public invoke(object invoke1) {
            this.invoke1 = invoke1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeResponse", Namespace="http://web.nts.nsp.nsi.dk/", Order=0)]
        public object invokeResponse1;
        
        public invokeResponse() {
        }
        
        public invokeResponse(object invokeResponse1) {
            this.invokeResponse1 = invokeResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NtsWSProviderChannel : SealTest.NSTWsProvider.NtsWSProvider, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NtsWSProviderClient : System.ServiceModel.ClientBase<SealTest.NSTWsProvider.NtsWSProvider>, SealTest.NSTWsProvider.NtsWSProvider {
        
        public NtsWSProviderClient() {
        }
        
        public NtsWSProviderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NtsWSProviderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NtsWSProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NtsWSProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SealTest.NSTWsProvider.invokeResponse SealTest.NSTWsProvider.NtsWSProvider.invoke(SealTest.NSTWsProvider.invoke request) {
            return base.Channel.invoke(request);
        }
        
        public object invoke(object invoke1) {
            SealTest.NSTWsProvider.invoke inValue = new SealTest.NSTWsProvider.invoke();
            inValue.invoke1 = invoke1;
            SealTest.NSTWsProvider.invokeResponse retVal = ((SealTest.NSTWsProvider.NtsWSProvider)(this)).invoke(inValue);
            return retVal.invokeResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SealTest.NSTWsProvider.invokeResponse> SealTest.NSTWsProvider.NtsWSProvider.invokeAsync(SealTest.NSTWsProvider.invoke request) {
            return base.Channel.invokeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SealTest.NSTWsProvider.invokeResponse> invokeAsync(object invoke1) {
            SealTest.NSTWsProvider.invoke inValue = new SealTest.NSTWsProvider.invoke();
            inValue.invoke1 = invoke1;
            return ((SealTest.NSTWsProvider.NtsWSProvider)(this)).invokeAsync(inValue);
        }
    }
}
