//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SealTest.SosiGWReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd")]
    public enum FaultCode {
        
        /// <remarks/>
        sosigw_no_valid_idcard_in_request,
        
        /// <remarks/>
        sosigw_missing_signinginfo_in_request,
        
        /// <remarks/>
        sosigw_syntax_error_in_request,
        
        /// <remarks/>
        sosigw_awaiting_signing,
        
        /// <remarks/>
        sosigw_no_valid_idcard_in_cache,
        
        /// <remarks/>
        sosigw_access_denied,
        
        /// <remarks/>
        sosigw_internal_error,
        
        /// <remarks/>
        sosigw_proxy_error,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sosi.dk/gw/2007.09.01", ConfigurationName="SosiGWReference.SosiGWFacade")]
    public interface SosiGWFacade {
        
        // CODEGEN: Generating message contract since the operation requestIdCardDigestForSigning is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sosi.dk/gw/2007.09.01#requestIdCardDigestForSigning", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealTest.SosiGWReference.FaultCode), Action="http://sosi.dk/gw/2007.09.01#requestIdCardDigestForSigning", Name="FaultCode", Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SealTest.SosiGWReference.requestIdCardDigestForSigningResponse1 requestIdCardDigestForSigning(SealTest.SosiGWReference.requestIdCardDigestForSigningRequest request);
        
        // CODEGEN: Generating message contract since the operation logout is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sosi.dk/gw/2007.09.01#logout")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void logout(SealTest.SosiGWReference.logoutRequest request);
        
        // CODEGEN: Generating message contract since the operation getValidIdCard is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sosi.dk/gw/2007.09.01#getValidIdCard", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealTest.SosiGWReference.FaultCode), Action="http://sosi.dk/gw/2007.09.01#getValidIdCard", Name="FaultCode", Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SealTest.SosiGWReference.getValidIdCardResponse getValidIdCard(SealTest.SosiGWReference.getValidIdCardRequest request);
        
        // CODEGEN: Generating message contract since the operation signIdCard is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sosi.dk/gw/2007.09.01#signIdCard", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealTest.SosiGWReference.FaultCode), Action="http://sosi.dk/gw/2007.09.01#signIdCard", Name="FaultCode", Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SealTest.SosiGWReference.signIdCardResponse1 signIdCard(SealTest.SosiGWReference.signIdCardRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class Security : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Timestamp timestampField;
        
        private AssertionType assertionField;
        
        private Signature signatureField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xs" +
            "d", Order=0)]
        public Timestamp Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:SAML:2.0:assertion", Order=1)]
        public AssertionType Assertion {
            get {
                return this.assertionField;
            }
            set {
                this.assertionField = value;
                this.RaisePropertyChanged("Assertion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=2)]
        public Signature Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("Signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xs" +
        "d")]
    public partial class Timestamp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime createdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class NameIDType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SubjectIdentifierType formatField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubjectIdentifierType Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("Format");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public enum SubjectIdentifierType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:cprnumber")]
        medcomcprnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:ynumber")]
        medcomynumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:pnumber")]
        medcompnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:skscode")]
        medcomskscode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:cvrnumber")]
        medcomcvrnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:communalnumber")]
        medcomcommunalnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:locationnumber")]
        medcomlocationnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:itsystemname")]
        medcomitsystemname,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:other")]
        medcomother,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class AssertionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string issuerField;
        
        private Subject subjectField;
        
        private Conditions conditionsField;
        
        private AttributeStatement[] attributeStatementField;
        
        private Signature signatureField;
        
        private System.DateTime issueInstantField;
        
        private decimal versionField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName", Order=0)]
        public string Issuer {
            get {
                return this.issuerField;
            }
            set {
                this.issuerField = value;
                this.RaisePropertyChanged("Issuer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Subject Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Conditions Conditions {
            get {
                return this.conditionsField;
            }
            set {
                this.conditionsField = value;
                this.RaisePropertyChanged("Conditions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeStatement", Order=3)]
        public AttributeStatement[] AttributeStatement {
            get {
                return this.attributeStatementField;
            }
            set {
                this.attributeStatementField = value;
                this.RaisePropertyChanged("AttributeStatement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=4)]
        public Signature Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("Signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime IssueInstant {
            get {
                return this.issueInstantField;
            }
            set {
                this.issueInstantField = value;
                this.RaisePropertyChanged("IssueInstant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class Subject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NameIDType nameIDField;
        
        private SubjectConfirmation subjectConfirmationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NameIDType NameID {
            get {
                return this.nameIDField;
            }
            set {
                this.nameIDField = value;
                this.RaisePropertyChanged("NameID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SubjectConfirmation SubjectConfirmation {
            get {
                return this.subjectConfirmationField;
            }
            set {
                this.subjectConfirmationField = value;
                this.RaisePropertyChanged("SubjectConfirmation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class SubjectConfirmation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ConfirmationMethod confirmationMethodField;
        
        private SubjectConfirmationData subjectConfirmationDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ConfirmationMethod ConfirmationMethod {
            get {
                return this.confirmationMethodField;
            }
            set {
                this.confirmationMethodField = value;
                this.RaisePropertyChanged("ConfirmationMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SubjectConfirmationData SubjectConfirmationData {
            get {
                return this.subjectConfirmationDataField;
            }
            set {
                this.subjectConfirmationDataField = value;
                this.RaisePropertyChanged("SubjectConfirmationData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public enum ConfirmationMethod {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:oasis:names:tc:SAML:2.0:cm:holder-of-key")]
        urnoasisnamestcSAML20cmholderofkey,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class SubjectConfirmationData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UsernameToken", typeof(UsernameToken), Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("KeyInfo", typeof(KeyInfo), Namespace="http://www.w3.org/2000/09/xmldsig#", Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class UsernameToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName", Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName", Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string), DataType="NMTOKEN", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509Data", typeof(X509Data), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509Data : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string), DataType="NMTOKEN", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509Certificate", typeof(byte[]), DataType="base64Binary", Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class Conditions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime notBeforeField;
        
        private System.DateTime notOnOrAfterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime NotBefore {
            get {
                return this.notBeforeField;
            }
            set {
                this.notBeforeField = value;
                this.RaisePropertyChanged("NotBefore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime NotOnOrAfter {
            get {
                return this.notOnOrAfterField;
            }
            set {
                this.notOnOrAfterField = value;
                this.RaisePropertyChanged("NotOnOrAfter");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class AttributeStatement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Attribute[] attributeField;
        
        private AttributeStatementID idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute", Order=0)]
        public Attribute[] Attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
                this.RaisePropertyChanged("Attribute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AttributeStatementID id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class Attribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string attributeValueField;
        
        private AttributeName nameField;
        
        private SubjectIdentifierType nameFormatField;
        
        private bool nameFormatFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AttributeValue {
            get {
                return this.attributeValueField;
            }
            set {
                this.attributeValueField = value;
                this.RaisePropertyChanged("AttributeValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AttributeName Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubjectIdentifierType NameFormat {
            get {
                return this.nameFormatField;
            }
            set {
                this.nameFormatField = value;
                this.RaisePropertyChanged("NameFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NameFormatSpecified {
            get {
                return this.nameFormatFieldSpecified;
            }
            set {
                this.nameFormatFieldSpecified = value;
                this.RaisePropertyChanged("NameFormatSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public enum AttributeName {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sosi:IDCardID")]
        sosiIDCardID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sosi:IDCardVersion")]
        sosiIDCardVersion,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sosi:IDCardType")]
        sosiIDCardType,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sosi:AuthenticationLevel")]
        sosiAuthenticationLevel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sosi:OCESCertHash")]
        sosiOCESCertHash,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserCivilRegistrationNumber")]
        medcomUserCivilRegistrationNumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserGivenName")]
        medcomUserGivenName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserSurName")]
        medcomUserSurName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserEmailAddress")]
        medcomUserEmailAddress,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserRole")]
        medcomUserRole,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserOccupation")]
        medcomUserOccupation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserAuthorizationCode")]
        medcomUserAuthorizationCode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:CareProviderID")]
        medcomCareProviderID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:CareProviderName")]
        medcomCareProviderName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:ITSystemName")]
        medcomITSystemName,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public enum AttributeStatementID {
        
        /// <remarks/>
        IDCardData,
        
        /// <remarks/>
        UserLog,
        
        /// <remarks/>
        SystemLog,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class Signature : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SignedInfo signedInfoField;
        
        private byte[] signatureValueField;
        
        private KeyInfo keyInfoField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SignedInfo SignedInfo {
            get {
                return this.signedInfoField;
            }
            set {
                this.signedInfoField = value;
                this.RaisePropertyChanged("SignedInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] SignatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
                this.RaisePropertyChanged("SignatureValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public KeyInfo KeyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
                this.RaisePropertyChanged("KeyInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CanonicalizationMethod canonicalizationMethodField;
        
        private SignatureMethod signatureMethodField;
        
        private Reference[] referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CanonicalizationMethod CanonicalizationMethod {
            get {
                return this.canonicalizationMethodField;
            }
            set {
                this.canonicalizationMethodField = value;
                this.RaisePropertyChanged("CanonicalizationMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SignatureMethod SignatureMethod {
            get {
                return this.signatureMethodField;
            }
            set {
                this.signatureMethodField = value;
                this.RaisePropertyChanged("SignatureMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference", Order=2)]
        public Reference[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("Reference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class CanonicalizationMethod : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CanonicalizationMethodAlgorithm algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CanonicalizationMethodAlgorithm Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
                this.RaisePropertyChanged("Algorithm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public enum CanonicalizationMethodAlgorithm {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/TR/2001/REC-xml-c14n-20010315")]
        httpwwww3orgTR2001RECxmlc14n20010315,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2001/10/xml-exc-c14n#")]
        httpwwww3org200110xmlexcc14n,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureMethod : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SignatureMethodAlgorithm algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SignatureMethodAlgorithm Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
                this.RaisePropertyChanged("Algorithm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public enum SignatureMethodAlgorithm {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#rsa-sha1")]
        httpwwww3org200009xmldsigrsasha1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class Reference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Transforms transformsField;
        
        private DigestMethod digestMethodField;
        
        private byte[] digestValueField;
        
        private string uRIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Transforms Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
                this.RaisePropertyChanged("Transforms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DigestMethod DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
                this.RaisePropertyChanged("DigestMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
                this.RaisePropertyChanged("DigestValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
                this.RaisePropertyChanged("URI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class Transforms : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TransformsTransform[] transformField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transform", Order=0)]
        public TransformsTransform[] Transform {
            get {
                return this.transformField;
            }
            set {
                this.transformField = value;
                this.RaisePropertyChanged("Transform");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class TransformsTransform : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
                this.RaisePropertyChanged("Algorithm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DigestMethod : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DigestMethodAlgorithm algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DigestMethodAlgorithm Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
                this.RaisePropertyChanged("Algorithm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public enum DigestMethodAlgorithm {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#rsa-sha1")]
        httpwwww3org200009xmldsigrsasha1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sosi.dk/gw/2007.09.01")]
    public partial class requestIdCardDigestForSigningResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] digestValueField;
        
        private string browserUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", DataType="base64Binary", Order=0)]
        public byte[] DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
                this.RaisePropertyChanged("DigestValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string BrowserUrl {
            get {
                return this.browserUrlField;
            }
            set {
                this.browserUrlField = value;
                this.RaisePropertyChanged("BrowserUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requestIdCardDigestForSigningRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public SealTest.SosiGWReference.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sosi.dk/gw/2007.09.01", Order=0)]
        public string requestIdCardDigestForSigningRequestBody;
        
        public requestIdCardDigestForSigningRequest() {
        }
        
        public requestIdCardDigestForSigningRequest(SealTest.SosiGWReference.Security Security, string requestIdCardDigestForSigningRequestBody) {
            this.Security = Security;
            this.requestIdCardDigestForSigningRequestBody = requestIdCardDigestForSigningRequestBody;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requestIdCardDigestForSigningResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sosi.dk/gw/2007.09.01", Order=0)]
        public SealTest.SosiGWReference.requestIdCardDigestForSigningResponse requestIdCardDigestForSigningResponse;
        
        public requestIdCardDigestForSigningResponse1() {
        }
        
        public requestIdCardDigestForSigningResponse1(SealTest.SosiGWReference.requestIdCardDigestForSigningResponse requestIdCardDigestForSigningResponse) {
            this.requestIdCardDigestForSigningResponse = requestIdCardDigestForSigningResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public SealTest.SosiGWReference.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sosi.dk/gw/2007.09.01", Order=0)]
        public string logoutRequestBody;
        
        public logoutRequest() {
        }
        
        public logoutRequest(SealTest.SosiGWReference.Security Security, string logoutRequestBody) {
            this.Security = Security;
            this.logoutRequestBody = logoutRequestBody;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidIdCardRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public SealTest.SosiGWReference.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sosi.dk/gw/2007.09.01", Order=0)]
        public string getValidIdCardRequestBody;
        
        public getValidIdCardRequest() {
        }
        
        public getValidIdCardRequest(SealTest.SosiGWReference.Security Security, string getValidIdCardRequestBody) {
            this.Security = Security;
            this.getValidIdCardRequestBody = getValidIdCardRequestBody;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidIdCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getValidIdCardResponse", Namespace="http://sosi.dk/gw/2007.09.01", Order=0)]
        public SealTest.SosiGWReference.AssertionType getValidIdCardResponse1;
        
        public getValidIdCardResponse() {
        }
        
        public getValidIdCardResponse(SealTest.SosiGWReference.AssertionType getValidIdCardResponse1) {
            this.getValidIdCardResponse1 = getValidIdCardResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sosi.dk/gw/2007.09.01")]
    public partial class signIdCardRequestBody : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] signatureValueField;
        
        private KeyInfo keyInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", DataType="base64Binary", Order=0)]
        public byte[] SignatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
                this.RaisePropertyChanged("SignatureValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=1)]
        public KeyInfo KeyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
                this.RaisePropertyChanged("KeyInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sosi.dk/gw/2007.09.01")]
    public enum signIdCardResponse {
        
        /// <remarks/>
        ok,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signIdCardRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public SealTest.SosiGWReference.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sosi.dk/gw/2007.09.01", Order=0)]
        public SealTest.SosiGWReference.signIdCardRequestBody signIdCardRequestBody;
        
        public signIdCardRequest() {
        }
        
        public signIdCardRequest(SealTest.SosiGWReference.Security Security, SealTest.SosiGWReference.signIdCardRequestBody signIdCardRequestBody) {
            this.Security = Security;
            this.signIdCardRequestBody = signIdCardRequestBody;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signIdCardResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sosi.dk/gw/2007.09.01", Order=0)]
        public SealTest.SosiGWReference.signIdCardResponse signIdCardResponse;
        
        public signIdCardResponse1() {
        }
        
        public signIdCardResponse1(SealTest.SosiGWReference.signIdCardResponse signIdCardResponse) {
            this.signIdCardResponse = signIdCardResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SosiGWFacadeChannel : SealTest.SosiGWReference.SosiGWFacade, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SosiGWFacadeClient : System.ServiceModel.ClientBase<SealTest.SosiGWReference.SosiGWFacade>, SealTest.SosiGWReference.SosiGWFacade {
        
        public SosiGWFacadeClient() {
        }
        
        public SosiGWFacadeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SosiGWFacadeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SosiGWFacadeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SosiGWFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SealTest.SosiGWReference.requestIdCardDigestForSigningResponse1 SealTest.SosiGWReference.SosiGWFacade.requestIdCardDigestForSigning(SealTest.SosiGWReference.requestIdCardDigestForSigningRequest request) {
            return base.Channel.requestIdCardDigestForSigning(request);
        }
        
        public SealTest.SosiGWReference.requestIdCardDigestForSigningResponse requestIdCardDigestForSigning(SealTest.SosiGWReference.Security Security, string requestIdCardDigestForSigningRequestBody) {
            SealTest.SosiGWReference.requestIdCardDigestForSigningRequest inValue = new SealTest.SosiGWReference.requestIdCardDigestForSigningRequest();
            inValue.Security = Security;
            inValue.requestIdCardDigestForSigningRequestBody = requestIdCardDigestForSigningRequestBody;
            SealTest.SosiGWReference.requestIdCardDigestForSigningResponse1 retVal = ((SealTest.SosiGWReference.SosiGWFacade)(this)).requestIdCardDigestForSigning(inValue);
            return retVal.requestIdCardDigestForSigningResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SealTest.SosiGWReference.SosiGWFacade.logout(SealTest.SosiGWReference.logoutRequest request) {
            base.Channel.logout(request);
        }
        
        public void logout(SealTest.SosiGWReference.Security Security, string logoutRequestBody) {
            SealTest.SosiGWReference.logoutRequest inValue = new SealTest.SosiGWReference.logoutRequest();
            inValue.Security = Security;
            inValue.logoutRequestBody = logoutRequestBody;
            ((SealTest.SosiGWReference.SosiGWFacade)(this)).logout(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SealTest.SosiGWReference.getValidIdCardResponse SealTest.SosiGWReference.SosiGWFacade.getValidIdCard(SealTest.SosiGWReference.getValidIdCardRequest request) {
            return base.Channel.getValidIdCard(request);
        }
        
        public SealTest.SosiGWReference.AssertionType getValidIdCard(SealTest.SosiGWReference.Security Security, string getValidIdCardRequestBody) {
            SealTest.SosiGWReference.getValidIdCardRequest inValue = new SealTest.SosiGWReference.getValidIdCardRequest();
            inValue.Security = Security;
            inValue.getValidIdCardRequestBody = getValidIdCardRequestBody;
            SealTest.SosiGWReference.getValidIdCardResponse retVal = ((SealTest.SosiGWReference.SosiGWFacade)(this)).getValidIdCard(inValue);
            return retVal.getValidIdCardResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SealTest.SosiGWReference.signIdCardResponse1 SealTest.SosiGWReference.SosiGWFacade.signIdCard(SealTest.SosiGWReference.signIdCardRequest request) {
            return base.Channel.signIdCard(request);
        }
        
        public SealTest.SosiGWReference.signIdCardResponse signIdCard(SealTest.SosiGWReference.Security Security, SealTest.SosiGWReference.signIdCardRequestBody signIdCardRequestBody) {
            SealTest.SosiGWReference.signIdCardRequest inValue = new SealTest.SosiGWReference.signIdCardRequest();
            inValue.Security = Security;
            inValue.signIdCardRequestBody = signIdCardRequestBody;
            SealTest.SosiGWReference.signIdCardResponse1 retVal = ((SealTest.SosiGWReference.SosiGWFacade)(this)).signIdCard(inValue);
            return retVal.signIdCardResponse;
        }
    }
}
